from getEmbeddingsAndSimilarity import getThreeModelsSimilarities

##############
##############
## POLÍTICA ##
###############
###############
title_ref = "Pereira conta com Matias"
text_ref = "Autarca mantém confiança que foi retirada pelo PSD Concelhia social-democrata afirma estar a demarcar-se de um \"projecto vazio e oco\". Vítor Pereira continua \"obviamente\" a contar com a colaboração do vereador eleito pelo PSD e diz que a decisão da estrutura \"laranja\" visa \"criar espaço para a candidatura\" a apresentar à Câmara da Covilhã. (Noticia na edição desta semana do NC)"
title_plus_text_ref = title_ref + ". " + text_ref

# GOOD
title_1 = "Orçamento de 35 milhões aprovado"
text_1 = "Assembleia Municipal aprova orçamento que Vítor Pereira classifica de \"realista e possível\" A Assembleia Municipal da Covilhã aprovou na passada terça-feira, 29 de Dezembro, o Orçamento e grandes opções para 2016, da autarquia, que contempla uma verba global de 35 milhões de euros. Um pouco superior ao ano que passou, que foi de 34,7 milhões de euros. O documento mereceu o voto favorável de PS, presidentes de Junta, a abstenção de dois deputados do PSD e voto contra do MAC e CDU. \"Este é o orçamento possível. É realista e consentâneo com o momento que estamos a viver. Este Quadro de Apoio ainda não terminou, o novo ainda não entrou, pelo que fomos cautelosos, num ano de incertezas em que não sabemos ainda que projectos podemos negociar. Mas estou convencido que poderemos candidatar os que consideramos fulcrais\" diz o autarca covilhanense. Que reafirma que a prioridade é \"o saneamento financeiro das contas do município. Estamos a abater, em média, por ano, 8,5 milhões de euros. E espero até final do mandato ter menos 35 milhões de dívida, para assim poder pensar no futuro\" frisa. (Artigo completo na edição papel)"
title_plus_text_1 = title_1 + ". " + text_1

# GOOD
title_2 = "Dívida aumentou"
text_2 = "Aprovadas contas consolidadas da autarquia covilhanense A Assembleia Municipal da Covilhã aprovou por maioria, com o voto contra da oposição, as Contas Consolidadas de 2015, que se traduzem num resultado negativo de 2,5 milhões de euros e um aumento da dívida em sete milhões de euros, que se situa agora nos 89 milhões de euros. Um acréscimo que o presidente justifica com as dívidas que \"caíram em cima\" do município. Vítor Pereira enaltece, por isso, o \"esforço de consolidação\" feito, na ordem dos oito milhões de euros. O Relatório de Gestão das Contas Consolidadas de 2015 foi aprovado com 23 votos a favor, do PS e presidentes de junta, nove contra, do MAC, PSD e PCP, e uma abstenção. (Notícia completa na edição papel)"
title_plus_text_2 = title_2 + ". " + text_2

# GOOD
title_3 = "Carlos Martins crítico"
text_3 = "Vereador aborda redefinição de funções e pelouros na autarquia O vereador Carlos Martins não deixou de, na última reunião pública do executivo covilhanense este ano, na passada sexta-feira, 18, deixar algumas críticas à recente redistribuição de pelouros e funções executivas efectuada pelo presidente da autarquia, Vítor Pereira. Recorde-se que há cerca de três semanas, o presidente da Câmara Municipal da Covilhã comunicou o despacho de atribuição de funções executivas a Nelson Silva, que passa a assumir o pelouro do Planeamento Estratégico, a meio tempo. Para além da nomeação do vereador eleito pelo Movimento Acreditar Covilhã (MAC) e ex-militante socialista, o \"reforço da equipa, para que seja mais eficiente\", passou também pela delegação de competências no assessor Rui Moreira, no chefe de gabinete José Miguel Oliveira e no adjunto Hélio Fazendeiro, explicou o presidente, Vítor Pereira. A Joaquim Matias, eleito pelo PSD, foi atribuído mais um pelouro: o da Fiscalização Municipal, cuja equipa partilha o mesmo espaço do Urbanismo. \"Faz sentido que se articulem os dois serviços sobre a sua alçada\", justificou o presidente. Uma medida que Carlos Martins não deixou passar em claro. \"Quando me dão trabalho para fazer, eu faço. Se não me dão, não posso fazer. Já tive alguns pelouros\" ironizou Martins, que lembra ter sido eleito pelo PS e que não teria \"problemas\" em ter mais alguns. \"Começo a verificar que em algumas câmaras os vereadores não têm o poder que a população lhes deu. Os presidentes escolhem pessoas e atribuem-lhes pelouros\" criticou."
title_plus_text_3 = title_3 + ". " + text_3

# GOOD
title_4 = "Santos Silva suspende mandato"
text_4 = "Por período de um ano. Oposição diz ser sinal de desnorte da autarquia O presidente da Assembleia Municipal da Covilhã, Santos Silva, suspendeu por 365 dias o seu mandato à frente deste órgão. Partidos da oposição já reagiram à decisão. A secção do PSD da Covilhã acusa o executivo municipal covilhanense de \"falta de rumo estratégico\". \"A história da demissão anunciada comprova a falta de saber estar democrático. A Covilhã não pode ficar refém dos interesses pessoais e políticos de meia dúzia de eleitos locais. Anunciar a suspensão por 365 dias é um acto de profundo desrespeito pelos eleitores covilhanenses\", afirma, em comunicado, a comissão política de sessão do PSD Covilhã. Para o Movimento Acreditar Covilhã (MAC) a suspensão do mandato por parte do presidente da Assembleia Municipal da Covilhã, Manuel Santos Silva, é \"mais um momento de total desorientação desta gestão municipal\". A segunda força mais votada nas últimas eleições autárquicas diz que a as razões para a suspensão do mandato pelo período máximo permitido \"são conhecidas de todos\". \"Os processos que envolvem a família do senhor Professor Santos Silva e a Câmara Municipal da Covilhã\", acrescenta o MAC, aludindo ao acordo \"com contornos menos claros\" celebrado entre ambas as partes a propósito de uns terrenos no Canhoso. (Mais informação na edição papel)"
title_plus_text_4 = title_4 + ". " + text_4

# GOOD
title_5 = "Matias coloca lugar a disposição"
text_5 = "Vereador em permanência coloca lugar à disposição O vereador do PSD na Câmara da Covilhã, Joaquim Matias, acaba de colocar o seu lugar de vereador em permanência à disposição, na reunião pública do executivo que está a decorrer. Uma posição tomada após uma troca de palavras com o vereador socialista Carlos Martins. Um assunto que será discutido em reunião privada, a seguir ao encontro público da autarquia. Mais desenvolvimentos na edição da próxima semana do NC."
title_plus_text_5 = title_5 + ". " + text_5

# BAD
title_6 = "Ginásio vive há 103 anos"
text_6 = "Sexta-feira há assembleia geral eleitoral O Ginásio Clube da Covilhã realiza na próxima sexta-feira, 19, às 15 horas, a assembleia geral eleitoral que ficara adiada em Fevereiro devido à ausência de listas candidatas aos órgãos sociais da colectividade covilhanense, uma das mais antigas da cidade. Que assinala este mês 103 anos de vida. Carlos Barroca, actual presidente da direcção, após aquela reunião, deixou no ar a hipótese de se recandidatar, embora alguns sócios se estivessem a mobilizar no sentido de formar uma lista. Na última reunião magna, os cerca de 20 sócios presentes aprovaram ainda por unanimidade o relatório e contas de 2015, com um saldo positivo de 3.370. 28 euros. O Ginásio é das colectividades mais antigas da cidade e os seus bailes eram dos mais afamados da Covilhã. Especialmente os de final de ano e os de Carnaval, o que suscitavam a curiosidade de muita gente. Na sua génese, o Ginásio era um clube elitista, vedado a pessoas como os operários fabris, e teve, entre outras modalidades, a esgrima, o atletismo, basquetebol e ténis de mesa. Situada no centro da cidade, a sua sede é hoje o local onde alguns se encontram para jogar snooker ou jogos de mesa. Chegou a ter mais de 700 sócios, actualmente tem 300."
title_plus_text_6 = title_6 + ". " + text_6

# BAD
title_7 = "O livro perdido da Covilhã"
text_7 = "Um povo que o podia ser de criadores acaba por ser uma matilha de aldrabões Eduardo Lourenço tem-nos questionado permanentemente sobre a nossa origem / condições ou inevitabilidade quiçá o nosso destino quase fatal como pessoas e País. Um destes dias fui ouvir Gabriel Magalhães que conhecia de alguns escritos e me deixou maravilhado ante a riqueza de pensamento reflectido em \"Madrugada na tua alma\". A partir desta obra realço alguns aspectos que utilizarei como termo de análise / comparação. Parafraseando sem distorcer, \"não admira que num País como o nosso, tão dado a esquecer os seus talentos, possuidores de enormes qualidades, nos deparemos amiúde com essas virtudes transformadas em defeitos\". A nossa criatividade que caracteriza esse excesso de imaginação dos portugueses \"só em Portugal podia haver um Fernando Pessoa\". Mas é pena que a criatividade, hoje, só nos serve para o nosso defeito de trafulhice. Um povo que o podia ser de criadores acaba por ser uma matilha de aldrabões. Não deixa de ser soberba a questão que se coloca: \"Já imaginaram o que seria o nosso Portugal se a energia que se aplica na vigarice se orientasse para actividades dignas?\" Para de imediato concordar com o distinto professor e (re) sublinhar o quanto este pormenor mostra como \"a nossa criatividade, que podia servir para tanta coisa boa, se está a reduzir a uma mera trafulhice do mero oportunismo.\" Em tempos não muito recuados, quando uma figura pública veio a terreiro lançar a confusão sobre a alegada orientação sexual de José Sócrates, atribuindo-lhe o gosto por outros colos, fiquei bastante indignado com essa atitude e o resultado da opinião pública eleitoral, não o foi menor. Nos alvores do Verão passado uma \"alegada caravana\" da revista Visão, e a pretexto de uma questão pessoal, se veio desse modo ofender a dignidade de Carlos Pinto, recorrendo ao nome de seu pai, de forma vil e despeitada. Manifestei-lhe de imediato a minha solidariedade e indignação pelo ato. Não gostei como é óbvio. Os ataques recentes a Carlos Casteleiro não passam de mais um desses procedimentos atávicos, onde a sua grandeza e heroicidade, é transformada em farsa e Carnaval de \"pretensos políticos a fazerem de conta que são de vistas cultas, requisitados intelectuais, e não passam de espertalhões com uma ou duas ideias eleitorais\". Termino segundo Gabriel Magalhães, \"Os verdadeiros heróis são pessoas humildes. Lúcidos. Que fazem aquilo que têm a fazer, sem dar nas vistas. A heroicidade a sério não se vê: não tem palco incluído\". \"A discrição é o terreno próprio da verdadeira valentia. Quem precisa de palmas é porque é covarde. Ou de como ser português, também tem sido isto: aprender a viver com a doença da portugalidade.\" Mas não devia ser isto, não devia…e fico triste, por isso\"."
title_plus_text_7 = title_7 + ". " + text_7

# BAD
title_8 =  "Misericórdia lança Cartão do Irmão"
text_8 = "Iniciativa da Santa Casa confere benefícios em mais de 40 empresas e serviços dos mais diversos sectores de actividade Os irmãos da Santa Casa da Misericórdia da Covilhã com as quotas em dia têm, desde o dia 15 de Maio, acesso a um conjunto de descontos em mais de 40 empresas, de diversos sectores de actividade, parceiras do Cartão do Irmão, iniciativa apresentada na passada sexta-feira, 29. O objectivo, segundo o provedor, José Neto Freire, é \"dignificar e enaltecer\" o papel de Irmão e Irmã na Misericórdia da Covilhã e ir além da preocupação com o dia-a-dia da instituição. O responsável frisa ainda a importância dos membros da Santa Casa no contributo que podem dar para o desenvolvimento e sustentabilidade da secular organização. \"Pretendemos ter uma irmandade viva\", acentua o provedor. \"Preocupamo-nos que esta casa esteja com as portas abertas\", acrescenta. \"Acreditamos que o cartão ajudará a aproximar os irmãos da irmandade e que mais se queiram aproximar\", continua José Neto Freire. (Noticia completa na edição papel)"
title_plus_text_8 = title_8 + ". " + text_8

# BAD
title_9 = "Uma escola de música com 200 anos"
text_9 = "A Banda do Paul completa esta quinta-feira, 30, dois séculos de existência David benze-se, tira o trompete do estojo aveludado e desce, nervoso, as escadas, para a audição onde vai mostrar o que já aprendeu na Escola de Música da Banda do Paul, frequentada por 14 crianças. Uns mais descontraídos que outros, todos denotam a responsabilidade de tocar para um auditório lotado. Há quem aperte exageradamente o bocal na mão, à espera da sua vez, quem fique estático a rever a pauta, quem fique irrequieto até ser chamado. Na sala de ensaios, com as paredes forradas com caixas de ovos, para melhorar a insonorização, Santa Cecília em lugar de destaque, ao lado do quadro, e as estantes arrumadas a um canto, para dar lugar às cadeiras onde as famílias se sentam, os sons não saem ainda com fluidez, mas cada curta actuação é aplaudida efusivamente, num gesto de incentivo. As debilidades, as notas ao lado e alguns enganos são desvalorizados. O que importa, num sistema de ensino em que as crianças começam a mexer nos instrumentos ao mesmo tempo que aprendem solfejo, para não se saturarem, é acentuar a progressão já feita. \"É tão bom vê-los assim evoluir de uma audição para a outra\", incita Cidália Barata, a presidente da instituição paulense que esta quinta-feira, 30, completa 200 anos. Ao olhar para os mais novos, a dirigente, que entrou para a banda aos 11 anos para aprender trompete, vislumbra a necessária renovação e vê a escola como \"o garante\" do futuro. (Reportagem completa na edição papel)"
title_plus_text_9 = title_9 + ". " + text_9

# BAD
title_10 = "Chaló mais satisfeito com opções no plantel"
text_10 = "Técnico confia num bom campeonato Francisco Chaló, treinador do Sporting da Covilhã, da II Liga, diz que a chegada tardia de vários jogadores dificultou o seu trabalho, mas afirma sentir-se agora \"mais satisfeito\" e com matéria-prima para fazer um bom campeonato. O técnico lembra que alguns jogadores têm apenas cinco semanas de trabalho, quando o grupo começou a treinar há mais de três meses, e frisa que a falta de opções o condicionou, por exemplo na escolha do esquema táctico, por falta de avançados. \"Agora há mais opções e posso definir algumas coisas em função daquilo que tenho, e não do que me falta. Nesta altura há matéria-prima e o Francisco Chaló é um treinador mais satisfeito para desenvolver o seu trabalho, coisa que há um mês não era\", disse o treinador serrano. Os \"leões da serra\" foram eliminados na Taça da Liga e na Taça de Portugal, mas o treinador considera que o desempenho na II Liga \"até está a melhorar\" em relação ao ano passado, sublinhando o desempenho fora. A equipa tem apenas menos um ponto que na 9ª jornada da época transacta, \"mas tem mais jogos fora e estamos a apenas três pontos dos pontos conseguidos em casa do adversário em toda a primeira volta\", realça o técnico, optimista com a evolução da equipa. \"Nós acreditamos muito em nós e acho que temos crédito suficiente para acreditarmos em nós\", disse Francisco Chaló. (Artigo completo na edição papel)"
title_plus_text_10 = title_10 + ". " + text_10

titles = [title_1, title_2, title_3, title_4, title_5, title_6, title_7, title_8, title_9, title_10]
texts = [text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10]
titles_plus_texts = [title_plus_text_1, title_plus_text_2, title_plus_text_3, title_plus_text_4, title_plus_text_5, title_plus_text_6, title_plus_text_7, title_plus_text_8, title_plus_text_9, title_plus_text_10]

getThreeModelsSimilarities(title_ref=title_ref, text_ref=text_ref, title_plus_text_ref=title_plus_text_ref, titles=titles, texts=texts, titles_plus_texts=titles_plus_texts, type_name="POLITICA")